#!/bin/sh

set -eu

METABASE_VERSION=`cat ./version`
METABASE_DIR="$1/target/uberjar"
METABASE_JAR="$METABASE_DIR/metabase.jar"
METABASE_URL="http://downloads.metabase.com/v$METABASE_VERSION/metabase.jar"

mkdir -p $METABASE_DIR

echo -n "-----> Downloading Metabase... from $METABASE_URL to $METABASE_JAR"
curl -s --retry 3 -o $METABASE_JAR -L $METABASE_URL
echo "done"

METABASE_DEPLOY_URL="https://github.com/metabase/metabase-deploy/archive/v$METABASE_VERSION.tar.gz"
echo -n "-----> Downloading Metabase deploy... from $METABASE_DEPLOY_URL to $1"
curl -s --retry 3 -o "metabase.tar.gz" -L $METABASE_DEPLOY_URL
tar -xzf metabase.tar.gz
rm metabase.tar.gz
mv metabase-deploy-$METABASE_VERSION metabase
echo "done"
